{{- if and .Values.rbac.enabled (not .Values.rbac.existingServiceAccountName) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ template "registry-creds.fullname" . }}
rules:
    - apiGroups:
          - ""
      resources:
          - namespaces
      verbs:
          - list
          - watch
    - apiGroups:
          - ""
      resources:
          - secrets
      verbs:
          - create
          - get
          - update
    - apiGroups:
          - ""
      resources:
          - serviceaccounts
      verbs:
          - get
          - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
    name: {{ template "registry-creds.fullname" . }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ template "registry-creds.fullname" . }}
subjects:
    - kind: ServiceAccount
      name: {{ template "registry-creds.fullname" . }}
      namespace: kube-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "registry-creds.fullname" . }}
    namespace: kube-system
{{- end }}
